name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_NAME: ecom-saga
  AWS_REGION: ap-south-1
  AWS_ROLE_ARN: arn:aws:iam::227091671010:role/ecom-saga-github-actions-role

jobs:
  build-and-deploy:
    name: Build and Deploy Microservices
    runs-on: ubuntu-latest

    # Required for OIDC keyless authentication
    permissions:
      id-token: write
      contents: read

    # We use a matrix to run this job in parallel for all 4 microservices
    strategy:
      matrix:
        service: 
          - order-producer-service
          - order-inventory-service
          - order-payment-service
          - order-notification-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image locally
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.PROJECT_NAME }}/${{ matrix.service }}
          IMAGE_TAG: latest
        run: |
          echo "Building ${{ matrix.service }}..."
          cd ${{ matrix.service }}
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.PROJECT_NAME }}/${{ matrix.service }}
          IMAGE_TAG: latest
        run: |
          echo "Pushing image to ECR after successful security scan..."
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Force ECS Deployment (Zero Downtime Rolling Update)
        run: |
          echo "Triggering ECS to pull the new image for ${{ matrix.service }}..."
          aws ecs update-service \
            --cluster ${{ env.PROJECT_NAME }}-cluster \
            --service ${{ env.PROJECT_NAME }}-${{ matrix.service }}-service \
            --force-new-deployment
